# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create -n testenv python=3.7 -y
            conda activate testenv
            conda install pytest
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            conda activate testenv
            pytest -v --cov=calculator